apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketurl
spec:
  selector:
    matchLabels:
      app: pocketurl
  replicas: 3
  template:
    metadata:
      labels:
        app: pocketurl
    spec:
      containers:
      - name: pocketurl
        image: pocketurl:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: pocketurl-config
        - secretRef:
            name: mysql-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: pocketurl-service
spec:
  selector:
    app: pocketurl
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: None